name: ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cài pnpm đúng cách
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Build (skip if no script)
        run: |
          if jq -e '.scripts.build' package.json >/dev/null 2>&1; then
            pnpm run build
          else
            echo "No build script. Skipping."
          fi

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cài pnpm đúng cách
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Run tests
        env:
          KEY_PREFIX: aifao1:ci:
          USER_CACHE_TTL: '60'
          CACHE_ENABLED: '1'
        run: pnpm test
