name: ci
on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Use pnpm via corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.16.0 --activate
          pnpm -v
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build (skip if no script)
        run: |
          if jq -e '.scripts.build' package.json >/dev/null; then
            pnpm run -s build
          else
            echo "No build script -> skip"
          fi

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Use pnpm via corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.16.0 --activate
          pnpm -v
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run tests (fallback to node --test)
        run: |
          if jq -e '.scripts.test' package.json >/dev/null; then
            pnpm test
          else
            node --test
          fi

