name: ci
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install deps (tùy chọn)
        run: pnpm install --frozen-lockfile || true
      - name: Build (tùy chọn, nếu có script)
        run: |
          if [ -f package.json ] && jq -e '.scripts.build' package.json >/dev/null; then pnpm run build; else echo "no build script"; fi

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test
